name: custom_side_menu
description: "A highly customizable Flutter side menu widget with support for nested items, animations, and state management. Perfect for creating elegant navigation solutions."
version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
